name: 'Start MatrixOne'
description: 'Start a MatrixOne database'
author: 'FelixSeptem'
branding:
  icon: 'database'
  color: 'green'
input:
  host port:
    description: 'The port of host'
    required: false
    default: 6001
  container port:
    description: 'The port of container'
    required: false
    default: 6001
  tag:
    description: 'Docker hub tag of MatrixOne image'
    required: false
    default: 'latest'
  pending duration:
    description: 'Time duration after `docker run` command, wait for MO start'
    required: false
    default: '30s'
runs:
  using: 'docker'
  image: 'Dockerfile'
